### ISSUE TITLE
Installing 2.0.0 Alpha version

### ISSUE THREAD

**Issue by LosTigeros** [xfrocks/bdMedal#5]
Is it possible to install 2.0.0 Alpha version?
It shows me this error:
`Error: Class '\bdMedal\Setup' not found src/XF/AddOn/AddOn.php:452`
```
#0 src/XF/Admin/Controller/AddOn.php(626): XF\AddOn\AddOn->checkRequirements(NULL, NULL)
#1 src/XF/Admin/Controller/AddOn.php(363): XF\Admin\Controller\AddOn->getAddOnWarningsAndErrors(Object(XF\AddOn\AddOn))
#2 src/XF/Mvc/Dispatcher.php(249): XF\Admin\Controller\AddOn->actionInstall(Object(XF\Mvc\ParameterBag))
#3 src/XF/Mvc/Dispatcher.php(88): XF\Mvc\Dispatcher->dispatchClass('XF:AddOn', 'Install', 'json', Object(XF\Mvc\ParameterBag), 'listAddOns', Object(XF\Admin\Controller\AddOn), NULL)
#4 src/XF/Mvc/Dispatcher.php(41): XF\Mvc\Dispatcher->dispatchLoop(Object(XF\Mvc\RouteMatch))
#5 src/XF/App.php(1891): XF\Mvc\Dispatcher->run()
#6 src/XF.php(328): XF\App->run()
#7 admin.php(13): XF::runApp('XF\\Admin\\App')
#8 {main}
```

**Comment by daohoangson** [comment]
You should download and put it into addons/Xfrocks/Medal instead of addons/bdMedal. Then it should work.

**Comment by LosTigeros** [comment]
Yeah its got installed without problems.
